core/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^acceder$', views.acceder, name="acceder"),
    url(r'^registro/$', views.registro, name="registro"),
    url(r'^salir/$', views.salir, name="salir"),
]

empresa/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^sucursales/$', views.sucursales, name="sucursales"),
    url(r'^sucursales/nueva/$', views.nueva_sucursal, name="nueva_sucursal"),
    url(r'^sucursales/(?P<id>[\d]+)/editar/$', views.editar_sucursal, name="editar_sucursal"),
    url(r'^empleados/$', views.empleados, name="empleados"),
    url(r'^empleado/nuevo/$', views.nuevo_empleado_sucursal, name="nuevo_empleado_sucursal"),
    url(r'^empleado/(?P<id>[\d]+)/nuevo$', views.nuevo_empleado, name='nuevo_empleado'),
    url(r'^empleado/(?P<id>[\d]+)/editar/$', views.editar_empleado, name="editar_empleado"),
]

timbox_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'timbox_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls',  namespace="core")),
    url(r'', include('empresa.urls',  namespace="empresa")),
]

empresa/models.py
from django.db import models
from django.contrib.auth.models import User

class Sucursal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length = 100)
    calle = models.CharField(max_length = 50)
    colonia = models.CharField(max_length = 50)
    numero_exterior = models.IntegerField()
    numero_interior = models.IntegerField()
    ciudad = models.CharField(max_length = 50)
    pais = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length = 100)
    rfc = models.CharField(max_length = 50)
    puesto = models.CharField(max_length = 50)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

empresa/forms.py
from django import forms
from django.forms import ModelForm
from .models import Sucursal, Empleado

class SucursalForm(forms.ModelForm):
    class Meta:
        model = Sucursal
        fields = '__all__'
        exclude = ['user']

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        exclude = ['sucursal', 'user']

class EmpleadoSucursalForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = '__all__'
        exclude = ['user']

empresa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Sucursal, Empleado
from .forms import SucursalForm, EmpleadoForm, EmpleadoSucursalForm
from django.db.models import Count


@login_required()
def index(request):
    current_user = request.user
    sucursales = Sucursal.objects.filter(user=current_user).annotate(empleados=Count('empleado'))
    return render(request,'sucursales/index.html', locals())

@login_required()
def sucursales(request):
    current_user = request.user
    sucursales = Sucursal.objects.filter(user=current_user).annotate(empleados=Count('empleado'))
    return render(request,'sucursales/index.html', locals())

@login_required()
def empleados(request):
    current_user = request.user
    empleados = Empleado.objects.filter(user=current_user).all()
    return render(request,'empleados/index.html', locals())

@login_required()
def nueva_sucursal(request):
    current_user = request.user
    if request.method == "POST":
        form = SucursalForm(request.POST)
        if form.is_valid():
            sucursal = form.save(commit=False)
            sucursal.user = current_user
            sucursal.save()
            return redirect('/empleado/%d/nuevo' % sucursal.pk)
    else:
        form = SucursalForm()
    return render(request,'sucursales/nueva.html', locals())

@login_required()
def editar_sucursal(request, id):
    sucursal_edit = get_object_or_404(Sucursal, pk=id)
    es_edicion = False if sucursal_edit is None else True
    if request.method == "POST":
        form = SucursalForm(request.POST, instance=sucursal_edit)
        if form.is_valid():
            sucursal = form.save()
            return redirect(reverse('empresa:index'))
    else:
        form = SucursalForm(instance=sucursal_edit)
    return render(request,'sucursales/nueva.html', locals())

@login_required()
def nuevo_empleado(request, id):
    current_user = request.user
    if request.method == "POST":
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            empleado = form.save(commit=False)
            empleado.user = current_user
            empleado.sucursal_id = id
            empleado.save()
            return redirect('/empleado/%d/nuevo' % int(id))
    else:
        form = EmpleadoForm()
    return render(request,'empleados/nuevo.html', locals())

@login_required()
def nuevo_empleado_sucursal(request):
    current_user = request.user
    if request.method == "POST":
        form = EmpleadoSucursalForm(request.POST)
        if form.is_valid():
            empleado = form.save(commit=False)
            empleado.user = current_user
            empleado.save()
            return redirect(reverse('empresa:empleados'))
    else:
        form = EmpleadoSucursalForm()
    return render(request,'empleados/nuevo.html', locals())

@login_required()
def editar_empleado(request, id):
    empleado_edit = get_object_or_404(Empleado, pk=id)
    es_edicion = False if empleado_edit is None else True
    if request.method == "POST":
        form = EmpleadoForm(request.POST, instance=empleado_edit)
        if form.is_valid():
            empleado = form.save()
            return redirect(reverse('empresa:index'))
    else:
        form = EmpleadoForm(instance=empleado_edit)
    return render(request,'empleados/nuevo.html', locals())

empresa/templates/empleados/index.html
{% extends 'base/_layout.html' %}
{% block content %}
  {% if empleados %}
    <h1 class="page-header">Empleados</h1>
    <table class="table table-bordered table-striped">
      <thead>
        <th>#</th>
        <th>Nombre</th>
        <th>RFC</th>
        <th>Puesto</th>
        <th>Sucursal</th>
        <th></th>
      </thead>
      <tbody>
        {% for empleado in empleados %}
            <tr>
              <td>{{empleado.pk}}</td>
              <td>{{empleado.nombre}}</td>
              <td>{{empleado.rfc}}</td>
              <td>{{empleado.puesto}}</td>
              <td>{{empleado.sucursal}}</td>
              <td><a href="{% url 'empresa:editar_empleado' id=empleado.pk %}" class="btn btn-xs btn-inverse"><i class="glyphicon glyphicon-pencil"></i> Editar empleado</a></td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <a class="btn btn-default btn-lg btn-inverse" href="{% url 'empresa:nuevo_empleado_sucursal' %}"><i class="glyphicon glyphicon-plus"></i> Agregar empleado</a>
  {% else %}
    <div class="jumbotron">
      <h1><i class="glyphicon glyphicon-inbox"></i> No hay registros</h1>
    </div>
    <a class="btn btn-default btn-lg btn-inverse" href="{% url 'empresa:nuevo_empleado_sucursal' %}"><i class="glyphicon glyphicon-plus"></i> Agregar empleado</a>
  {% endif %}
{% endblock %}

empresa/templates/empleados/nuevo.html
{% extends 'base/_layout.html' %}
{% load widget_tweaks %}
{% block content %}
  {% if es_edicion %}
    <h1 class="page-header">Editar empleado</h1>
  {% else %}
    <h1 class="page-header">Nuevo empleado</h1>
  {% endif %}
  <span class="label label-danger" id="errors"></span><br>
  <span class="label label-danger" id="errors_pass"></span>
  <form id="form" method="post" action="">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}
        {% render_field field class+="form-control input-lg" %}
      </p>
    {% endfor %}
    <input type="submit" value="Registrar" class="btn btn-lg btn-default hidden"/>
    {% if es_edicion %}
      <input type="button" id="registrar" value="Guardar" class="btn btn-lg btn-inverse"/>
    {% else %}
      <input type="button" id="registrar" value="Registrar" class="btn btn-lg btn-inverse"/>
    {% endif %}
    <a href="{% url 'empresa:empleados' %}" class="btn btn-lg btn-inverse"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
  </form>
{% endblock %}
{% block javascript %}
    {% load staticfiles %}
    <script type="application/javascript" src="{% static "js/common.js" %}"></script>
    <script type="application/javascript" src="{% static "js/empleados.js" %}"></script>
{% endblock %}