core/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^acceder$', views.acceder, name="acceder"),
    url(r'^registro/$', views.registro, name="registro"),
    url(r'^salir/$', views.salir, name="salir"),
]

empresa/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^sucursales/$', views.sucursales, name="sucursales"),
    url(r'^sucursales/nueva/$', views.nueva_sucursal, name="nueva_sucursal"),
    url(r'^sucursales/(?P<id>[\d]+)/editar/$', views.editar_sucursal, name="editar_sucursal"),
    url(r'^empleados/$', views.empleados, name="empleados"),
    url(r'^empleado/nuevo/$', views.nuevo_empleado_sucursal, name="nuevo_empleado_sucursal"),
    url(r'^empleado/(?P<id>[\d]+)/nuevo$', views.nuevo_empleado, name='nuevo_empleado'),
    url(r'^empleado/(?P<id>[\d]+)/editar/$', views.editar_empleado, name="editar_empleado"),
]

timbox_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'timbox_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls',  namespace="core")),
    url(r'', include('empresa.urls',  namespace="empresa")),
]

empresa/models.py
from django.db import models
from django.contrib.auth.models import User

class Sucursal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length = 100)
    calle = models.CharField(max_length = 50)
    colonia = models.CharField(max_length = 50)
    numero_exterior = models.IntegerField()
    numero_interior = models.IntegerField()
    ciudad = models.CharField(max_length = 50)
    pais = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length = 100)
    rfc = models.CharField(max_length = 50)
    puesto = models.CharField(max_length = 50)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

empresa/forms.py
from django import forms
from django.forms import ModelForm
from .models import Sucursal, Empleado

class SucursalForm(forms.ModelForm):
    class Meta:
        model = Sucursal
        fields = '__all__'
        exclude = ['user']

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        exclude = ['sucursal', 'user']

class EmpleadoSucursalForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = '__all__'
        exclude = ['user']

empresa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Sucursal, Empleado
from .forms import SucursalForm, EmpleadoForm, EmpleadoSucursalForm
from django.db.models import Count


@login_required()
def index(request):
    current_user = request.user
    sucursales = Sucursal.objects.filter(user=current_user).annotate(empleados=Count('empleado'))
    return render(request,'sucursales/index.html', locals())

@login_required()
def sucursales(request):
    current_user = request.user
    sucursales = Sucursal.objects.filter(user=current_user).annotate(empleados=Count('empleado'))
    return render(request,'sucursales/index.html', locals())

@login_required()
def empleados(request):
    current_user = request.user
    empleados = Empleado.objects.filter(user=current_user).all()
    return render(request,'empleados/index.html', locals())

@login_required()
def nueva_sucursal(request):
    current_user = request.user
    if request.method == "POST":
        form = SucursalForm(request.POST)
        if form.is_valid():
            sucursal = form.save(commit=False)
            sucursal.user = current_user
            sucursal.save()
            return redirect('/empleado/%d/nuevo' % sucursal.pk)
    else:
        form = SucursalForm()
    return render(request,'sucursales/nueva.html', locals())

@login_required()
def editar_sucursal(request, id):
    sucursal_edit = get_object_or_404(Sucursal, pk=id)
    es_edicion = False if sucursal_edit is None else True
    if request.method == "POST":
        form = SucursalForm(request.POST, instance=sucursal_edit)
        if form.is_valid():
            sucursal = form.save()
            return redirect(reverse('empresa:index'))
    else:
        form = SucursalForm(instance=sucursal_edit)
    return render(request,'sucursales/nueva.html', locals())

@login_required()
def nuevo_empleado(request, id):
    current_user = request.user
    if request.method == "POST":
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            empleado = form.save(commit=False)
            empleado.user = current_user
            empleado.sucursal_id = id
            empleado.save()
            return redirect('/empleado/%d/nuevo' % int(id))
    else:
        form = EmpleadoForm()
    return render(request,'empleados/nuevo.html', locals())

@login_required()
def nuevo_empleado_sucursal(request):
    current_user = request.user
    if request.method == "POST":
        form = EmpleadoSucursalForm(request.POST)
        if form.is_valid():
            empleado = form.save(commit=False)
            empleado.user = current_user
            empleado.save()
            return redirect(reverse('empresa:empleados'))
    else:
        form = EmpleadoSucursalForm()
    return render(request,'empleados/nuevo.html', locals())

@login_required()
def editar_empleado(request, id):
    empleado_edit = get_object_or_404(Empleado, pk=id)
    es_edicion = False if empleado_edit is None else True
    if request.method == "POST":
        form = EmpleadoForm(request.POST, instance=empleado_edit)
        if form.is_valid():
            empleado = form.save()
            return redirect(reverse('empresa:index'))
    else:
        form = EmpleadoForm(instance=empleado_edit)
    return render(request,'empleados/nuevo.html', locals())

empresa/templates/base/_layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>App</title>

    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Raleway:400,700' rel='stylesheet' type='text/css'>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}" />

    {% block CSS %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'empresa:index' %}"><span>#</span>devApp</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'empresa:index' %}"><i class="glyphicon glyphicon glyphicon-user"></i> {{user.persona}}</a></li>
          <li><a href="{% url 'core:salir' %}"><i class="glyphicon glyphicon-off"></i> Salir</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li class="header"><a href="#">{{user.persona.empresa}} <span class="sr-only">(current)</span></a></li>
          <li><a href="{% url 'empresa:sucursales' %}">Sucursales</a></li>
          <li><a href="{% url 'empresa:empleados' %}">Empleados</a></li>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
<body>

{% load staticfiles %}
<script type="application/javascript" src="{% static "js/jquery.min.js" %}"></script>

{% block javascript %}
{% endblock %}
</body>
</html>