core/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^acceder$', views.acceder, name="acceder"),
    url(r'^registro/$', views.registro, name="registro"),
    url(r'^salir/$', views.salir, name="salir"),
]

timbox_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'timbox_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls',  namespace="core")),
    url(r'', include('empresa.urls',  namespace="empresa")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Persona(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    nombre_completo = models.CharField(max_length = 100)
    rfc = models.CharField(max_length = 20)
    empresa = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre_completo

core/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Persona

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        exclude = ['username', 'first_name', 'last_name', 'groups', 'user_permissions', 'is_staff', 'is_active', 'is_superuser', 'last_login', 'date_joined']

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        exclude = ['user']

core/views.py
from django.shortcuts import render,redirect,render_to_response,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .forms import UserForm, PersonaForm
from django.contrib.auth.hashers import make_password


#@login_required()
def acceder(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('empresa:index'))
            else:
                return HttpResponse("Cuenta desactivada.")
        else:
            message = "Datos incorrectos"
            return render(request,'account/login.html', locals())

    else:
        return render_to_response('account/login.html', {}, context)


def registro(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = PersonaForm(request.POST)
        if user_form.is_valid() * profile_form.is_valid():
            user = user_form.save(commit=False)
            user.username = user.email
            user.password = make_password(user_form.cleaned_data['password'])
            user.save()
            user_profile = profile_form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            return redirect(reverse('core:acceder'))
    else:
        user_form = UserForm()
        profile_form = PersonaForm()
    return render_to_response('account/registro.html', dict(user_form=user_form, profile_form=profile_form), context_instance=RequestContext(request))

@login_required
def salir(request):
    logout(request)
    return redirect(reverse('core:acceder'))

core/templates/base/_login_layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>App</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Raleway:400,700' rel='stylesheet' type='text/css'>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "css/cover.css" %}" />

    {% block CSS %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><span>#</span>devApp</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'core:acceder' %}">Acceder</a></li>
                  <li><a href="{% url 'core:registro' %}">Registro</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            {% block content %}
            {% endblock %}
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>by <a href="http://github.com/itsjesusurias">Jesus Urias</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

<body>

{% load staticfiles %}
<script type="application/javascript" src="{% static "js/jquery.min.js" %}"></script>

{% block javascript %}
{% endblock %}
</body>
</html>